update makefile to have make sync2caen

diff --git a/Perf Profiling Starter Files/Makefile b/Perf Profiling Starter Files/Makefile
--- a/Perf Profiling Starter Files/Makefile
+++ b/Perf Profiling Starter Files/Makefile
@@ -10,25 +10,47 @@
 ###################
 
 # IMPORTANT NOTES:
-#   1. Set EXECUTABLE to the command name given in the project specification.
+#   1. Set EXECUTABLE to the command name from the project specification.
 #   2. To enable automatic creation of unit test rules, your program logic
-#      (where main() is) should be in a file named project*.cpp or specified
-#      in the PROJECTFILE variable.
+#      (where main() is) should be in a file named project*.cpp or
+#      specified in the PROJECTFILE variable.
 #   3. Files you want to include in your final submission cannot match the
 #      test*.cpp pattern.
 
-# enables c++17 on CAEN
+#######################
+# TODO (begin) #
+#######################
+# Change 'youruniqname' to match your UM uniqname (no quote marks).
+UNIQNAME    = youruniqname
+
+# Change the right hand side of the identifier to match the project identifier
+# given in the project or lab specification.
+IDENTIFIER  = EEC50281EEC50281EEC50281EEC50281EEC50281
+
+EXECUTABLE  = profiling
+
+# The following line looks for a project's main() in files named project*.cpp,
+# executable.cpp (substituted from EXECUTABLE above), or main.cpp
+PROJECTFILE = $(or $(wildcard project*.cpp $(EXECUTABLE).cpp), main.cpp)
+# If main() is in another file delete line above, edit and uncomment below
+#PROJECTFILE = mymainfile.cpp
+#######################
+# TODO (end) #
+#######################
+
+# enables c++17 on CAEN or 281 autograder
 PATH := /usr/um/gcc-6.2.0/bin:$(PATH)
 LD_LIBRARY_PATH := /usr/um/gcc-6.2.0/lib64
 LD_RUN_PATH := /usr/um/gcc-6.2.0/lib64
 
-# TODO
-# Change EXECUTABLE to match the command name given in the project spec.
-EXECUTABLE 	= profiling
-DEBUG       = $(EXECUTABLE)_debug
+# This is the path from the CAEN home folder to where projects will be
+# uploaded. (eg. /home/mmdarden/eecs281/project1)
+# Change this if you prefer a different path.
+# REMOTE_PATH := eecs281_$(EXECUTABLE)_sync  # /home/mmdarden/eecs281_proj0_sync
+REMOTE_PATH := eecs281_$(EXECUTABLE)_sync
 
 # designate which compiler to use
-CXX			= g++
+CXX         = g++
 
 # list of test drivers (with main()) for development
 TESTSOURCES = $(wildcard test*.cpp)
@@ -36,50 +58,62 @@ TESTSOURCES = $(wildcard test*.cpp)
 TESTS       = $(TESTSOURCES:%.cpp=%)
 
 # list of sources used in project
-SOURCES 	= $(wildcard *.cpp)
+SOURCES     = $(wildcard *.cpp)
 SOURCES     := $(filter-out $(TESTSOURCES), $(SOURCES))
 # list of objects used in project
-OBJECTS		= $(SOURCES:%.cpp=%.o)
+OBJECTS     = $(SOURCES:%.cpp=%.o)
 
-# TODO
-# If main() is in a file named project*.cpp, use the following line
-#PROJECTFILE = $(or $(wildcard project*.cpp), nomain.cpp)
-# TODO
-# If main() is in another file delete the line above, edit and uncomment below
-PROJECTFILE = profiling.cpp
-
-# name of the tar ball created for submission
-PARTIAL_SUBMITFILE = partialsubmit.tar.gz
+# name of the tarball created for submission
 FULL_SUBMITFILE = fullsubmit.tar.gz
+PARTIAL_SUBMITFILE = partialsubmit.tar.gz
+UNGRADED_SUBMITFILE = ungraded.tar.gz
 
 # name of the perf data file, only used by the clean target
 PERF_FILE = perf.data*
 
-#Default Flags (would prefer -std=c++17 but Mac/Xcode/Clang doesn't support)
+#Default Flags (we prefer -std=c++17 but Mac/Xcode/Clang doesn't support)
 CXXFLAGS = -std=c++1z -Wconversion -Wall -Werror -Wextra -pedantic 
 
 # make release - will compile "all" with $(CXXFLAGS) and the -O3 flag
-#				 also defines NDEBUG so that asserts will not check
+#                also defines NDEBUG so that asserts will not check
 release: CXXFLAGS += -O3 -DNDEBUG
-release: all
+release: $(EXECUTABLE)
 
-# make debug - will compile "all" with $(CXXFLAGS) and the -g flag
-#              also defines DEBUG so that "#ifdef DEBUG /*...*/ #endif" works
-debug: EXECUTABLE := $(DEBUG)
+# make debug - will compile sources with $(CXXFLAGS) and the -g3 flag
+#              also defines DEBUG, so "#ifdef DEBUG /*...*/ #endif" works
 debug: CXXFLAGS += -g3 -DDEBUG
-debug: clean all
+debug:
+	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(EXECUTABLE)_debug
 
-# make profile - will compile "all" with $(CXXFLAGS) and the -pg flag
-profile: CXXFLAGS += -pg
-profile: clean all
+# make profile - will compile "all" with $(CXXFLAGS) and the -g3 and -O3 flags
+profile: CXXFLAGS += -g3 -O3
+profile:
+	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(EXECUTABLE)_profile
+	
+# make gprof - will compile "all" with $(CXXFLAGS) and the -pg (for gprof)
+gprof: CXXFLAGS += -pg
+gprof:
+	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(EXECUTABLE)_profile
 
 # make static - will perform static analysis in the matter currently used
 #               on the autograder
 static:
-	cppcheck --enable=all --suppress=missingIncludeSystem *.c* *.h*
+	cppcheck --enable=all --suppress=missingIncludeSystem \
+      $(SOURCES) *.h *.hpp
 
-# highest target; sews together all objects into executable
-all: $(EXECUTABLE)
+# make identifier - will check to ensure that all source code and header files
+#                   include the project identifier; skip subdirectories;
+#                   also removes old submit tarballs, they are outdated
+identifier:
+	@if [ $$(grep --include=*.{h,hpp,c,cpp} --exclude=xcode_redirect.hpp --directories=skip -L $(IDENTIFIER) * | wc -l) -ne 0 ]; then \
+		printf "Missing project identifier in file(s): "; \
+		echo `grep --include=*.{h,hpp,c,cpp} --directories=skip -L $(IDENTIFIER) *`; \
+		rm -f $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE); \
+		exit 1; \
+	fi
+
+# Build all executables
+all: release debug profile
 
 $(EXECUTABLE): $(OBJECTS)
 ifeq ($(EXECUTABLE), executable)
@@ -98,14 +132,14 @@ define make_tests
     endif
     SRCS = $$(filter-out $$(PROJECTFILE), $$(SOURCES))
     OBJS = $$(SRCS:%.cpp=%.o)
-    HDRS = $$(wildcard *.h)
+    HDRS = $$(wildcard *.h *.hpp)
     $(1): CXXFLAGS += -g3 -DDEBUG
     $(1): $$(OBJS) $$(HDRS) $(1).cpp
 	$$(CXX) $$(CXXFLAGS) $$(OBJS) $(1).cpp -o $(1)
 endef
 $(foreach test, $(TESTS), $(eval $(call make_tests, $(test))))
 
-alltests: clean $(TESTS)
+alltests: $(TESTS)
 
 # rule for creating objects
 %.o: %.cpp
@@ -113,28 +147,69 @@ alltests: clean $(TESTS)
 
 # make clean - remove .o files, executables, tarball
 clean:
-	rm -f $(OBJECTS) $(EXECUTABLE) $(DEBUG) $(TESTS) $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE) $(PERF_FILE)
+	rm -f $(OBJECTS) $(EXECUTABLE) $(EXECUTABLE)_debug $(EXECUTABLE)_profile \
+      $(TESTS) $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE) $(PERF_FILE) \
+      $(UNGRADED_SUBMITFILE)
 	rm -Rf *.dSYM
 
-# make partialsubmit.tar.gz - cleans, runs dos2unix, creates tarball omitting test cases
-PARTIAL_SUBMITFILES=$(filter-out $(TESTSOURCES), $(wildcard Makefile *.h *.cpp))
-$(PARTIAL_SUBMITFILE): $(PARTIAL_SUBMITFILES)
-	rm -f $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE)
-	-dos2unix $(PARTIAL_SUBMITFILES)
-	COPYFILE_DISABLE=true tar -vczf $(PARTIAL_SUBMITFILE) $(PARTIAL_SUBMITFILES)
-	@echo !!! WARNING: No test cases included. Use 'make fullsubmit' to include test cases. !!!
 
-# make fullsubmit.tar.gz - cleans, runs dos2unix, creates tarball including test cases
-FULL_SUBMITFILES=$(filter-out $(TESTSOURCES), $(wildcard Makefile *.h *.cpp test*.txt))
+# get a list of all files that might be included in a submit
+# different submit types can do additional filtering to remove unwanted files
+FULL_SUBMITFILES=$(filter-out $(TESTSOURCES), \
+                   $(wildcard Makefile *.h *.hpp *.cpp test*.txt))
+
+# make fullsubmit.tar.gz - cleans, runs dos2unix, creates tarball
+# including test files
 $(FULL_SUBMITFILE): $(FULL_SUBMITFILES)
-	rm -f $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE)
-	-dos2unix $(FULL_SUBMITFILES)
+	rm -f $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE) $(UNGRADED_SUBMITFILE)
 	COPYFILE_DISABLE=true tar -vczf $(FULL_SUBMITFILE) $(FULL_SUBMITFILES)
-	@echo !!! Final submission prepared, test cases included... READY FOR GRADING !!!
+	@echo !!! Final submission prepared, test files included... READY FOR GRADING !!!
+
+# make partialsubmit.tar.gz - cleans, creates tarball
+# omitting test files
+PARTIAL_SUBMITFILES=$(filter-out $(wildcard test*.txt), $(FULL_SUBMITFILES))
+$(PARTIAL_SUBMITFILE): $(PARTIAL_SUBMITFILES)
+	rm -f $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE) $(UNGRADED_SUBMITFILE)
+	COPYFILE_DISABLE=true tar -vczf $(PARTIAL_SUBMITFILE) \
+      $(PARTIAL_SUBMITFILES)
+	@echo !!! WARNING: No test files included. Use 'make fullsubmit' to include test files. !!!
+
+# make ungraded.tar.gz - cleans, creates tarball omitting test files, Makefile
+UNGRADED_SUBMITFILES=$(filter-out Makefile, $(PARTIAL_SUBMITFILES))
+$(UNGRADED_SUBMITFILE): $(UNGRADED_SUBMITFILES)
+	rm -f $(PARTIAL_SUBMITFILE) $(FULL_SUBMITFILE) $(UNGRADED_SUBMITFILE)
+	@touch __ungraded
+	COPYFILE_DISABLE=true tar -vczf $(UNGRADED_SUBMITFILE) \
+      $(UNGRADED_SUBMITFILES) __ungraded
+	@rm -f __ungraded
+	@echo !!! WARNING: This submission will not be graded. !!!
 
 # shortcut for make submit tarballs
-partialsubmit: $(PARTIAL_SUBMITFILE)
-fullsubmit: $(FULL_SUBMITFILE)
+fullsubmit: identifier $(FULL_SUBMITFILE)
+partialsubmit: identifier $(PARTIAL_SUBMITFILE)
+ungraded: identifier $(UNGRADED_SUBMITFILE)
+
+# REMOTE_PATH has default definition above
+sync2caen:
+ifeq ($(UNIQNAME), youruniqname)
+	@echo Edit UNIQNAME variable in Makefile.
+	@exit 1;
+endif
+	# Synchronize local files into target directory on CAEN
+	rsync \
+      -av \
+      --delete \
+      --exclude '*.o' \
+      --exclude '$(EXECUTABLE)' \
+      --exclude '$(EXECUTABLE)_debug' \
+      --exclude '$(EXECUTABLE)_profile' \
+      --exclude '.git*' \
+      --exclude '.vs*' \
+      --exclude '*.code-workspace' \
+      --filter=":- .gitignore" \
+      "."/ \
+      "$(UNIQNAME)@login.engin.umich.edu:'$(REMOTE_PATH)/'"
+	echo "Files synced to CAEN at ~/$(REMOTE_PATH)/"
 
 define MAKEFILE_HELP
 EECS281 Advanced Makefile Help
@@ -143,20 +218,27 @@ EECS281 Advanced Makefile Help
 
 * General usage
     1. Follow directions at each "TODO" in this file.
-       a. Set EXECUTABLE equal to the name given in the project specification.
+       a. Set EXECUTABLE equal to the name from the project specification.
        b. Set PROJECTFILE equal to the name of the source file with main()
        c. Add any dependency rules specific to your files.
     2. Build, test, submit... repeat as necessary.
 
 * Preparing submissions
-    A) To build 'partialsubmit.tar.gz', a tarball without tests used to find
-       buggy solutions in the autograder.  This is useful for faster autograder
-       runs during development and free submissions if the project does not
-       build.
-           $$ make partialsubmit
-    B) Build 'fullsubmit.tar.gz' a tarball complete with autograder test cases.
-       ALWAYS USE THIS FOR FINAL GRADING!  It is also useful when trying to
+    A) To build 'partialsubmit.tar.gz', a tarball without tests used to
        find buggy solutions in the autograder.
+
+           *** USE THIS ONLY FOR TESTING YOUR SOLUTION! ***
+
+       This is useful for faster autograder runs during development and
+       free submissions if the project does not build.
+           $$ make partialsubmit
+    B) Build 'fullsubmit.tar.gz' a tarball complete with autograder test
+       files.
+
+           *** ALWAYS USE THIS FOR FINAL GRADING! ***
+
+       It is also useful when trying to find buggy solutions in the
+       autograder.
            $$ make fullsubmit
 
 * Unit testing support
@@ -166,14 +248,22 @@ EECS281 Advanced Makefile Help
            $$ make test_input
            $$ make test3
            $$ make alltests        (this builds all test drivers)
-    C) If test drivers need special dependencies, they must be added manually.
-    D) IMPORTANT: NO SOURCE FILES THAT BEGIN WITH test WILL BE ADDED TO ANY
-       SUBMISSION TARBALLS.
+    C) If test drivers need special dependencies, they must be added
+       manually.
+    D) IMPORTANT: NO SOURCE FILES WITH NAMES THAT BEGIN WITH test WILL BE
+       ADDED TO ANY SUBMISSION TARBALLS.
 
 * Static Analysis support
     A) Matches current autograder style grading tests
     B) Usage:
            $$ make static
+
+* Sync to CAEN support
+    A) Requires an .ssh/config file with a login.engin.umich.edu host
+       defined, SSH Multiplexing enabled, and an open SSH connection.
+    B) Edit the REMOTE_BASEDIR variable if default is not preferred.
+    C) Usage:
+           $$ make sync2caen
 endef
 export MAKEFILE_HELP
 
@@ -193,15 +283,26 @@ help:
 # myclass.o: myclass.cpp myclass.h $(HEADERS)
 # project5.o: project5.cpp myclass.o $(HEADERS)
 #
+# SOME EXAMPLES
+#
+#test_thing: test_thing.cpp class.o functions.o
+#class.o: class.cpp class.h
+#functions.o: functions.cpp functions.h
+#project0.o: project0.cpp class.h functions.h
+#
+# THE COMPILER CAN GENERATE DEPENDENCIES FROM SOURCE CODE
+#
+# % g++ -std=c++1z -MM *.cpp
+#
 # ADD YOUR OWN DEPENDENCIES HERE
-
-# None needed, profiling.o automatically depends upon profiling.cpp
 
 ######################
 # TODO (end) #
 ######################
 
 # these targets do not create any files
-.PHONY: all release debug profile static clean alltests partialsubmit fullsubmit help
+.PHONY: all release debug profile gprof static clean alltests
+.PHONY: partialsubmit fullsubmit ungraded sync2caen help identifier
+
 # disable built-in rules
 .SUFFIXES:
